# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: eguelin <eguelin@student.42lyon.fr>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/01/27 19:24:50 by eguelin           #+#    #+#              #
#    Updated: 2024/03/03 14:24:24 by eguelin          ###   ########lyon.fr    #
#                                                                              #
# **************************************************************************** #

version: '3.8'

services:

  # Database service
  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb/
      args:
        - DB_ROOT_PASSWORD
        - DB_NAME
        - DB_USER
        - DB_PASSWORD
    env_file: .env
    image: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: always

  # Website service
  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress/
    env_file: .env
    image: wordpress
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always

  # Server service
  nginx:
    container_name: nginx
    build: requirements/nginx
    image: nginx
    env_file: .env
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception
    restart: always

volumes:

  # Volumes of the database
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'volumes/mariadb'

  # Volumes of the website and server
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'volumes/wordpress'

networks:

  # Network of the services
  inception:
    name: inception
    driver: bridge
