# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: eguelin <eguelin@student.42lyon.fr>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/01/27 19:24:50 by eguelin           #+#    #+#              #
#    Updated: 2024/02/15 17:14:20 by eguelin          ###   ########lyon.fr    #
#                                                                              #
# **************************************************************************** #

version: '3.8'

secrets:

  mariadb:
    build: ./requirements/mariadb
    ports:
      - 3036:3036
    volumes:
      - mariadb:/var/lib/mysql

  wordpress:
    build: ./requirements/wordpress
    ports:
      - 9000:9000
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb

  nginx:
    build: ./requirements/nginx
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress

volumes:

  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/eguelin/volumes'

  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/eguelin/volumes'
